// <auto-generated />
using HocTiengTrung.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HocTiengTrung.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("HocTiengTrung.Models.BaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenBaiHoc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaiHocs");
                });

            modelBuilder.Entity("HocTiengTrung.Models.CauHoiGhepTu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaiHocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CotBenPhai")
                        .HasColumnType("TEXT");

                    b.Property<string>("CotBenTrai")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.ToTable("CauHoiGhepTus");
                });

            modelBuilder.Entity("HocTiengTrung.Models.CauHoiGhepTu", b =>
                {
                    b.HasOne("HocTiengTrung.Models.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
